//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLEPEDIDO
    {
        public int idProducto { get; set; }
        public int idPedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PEDIDO PEDIDO1 { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
