//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOXSUCURSAL
    {
        public int idSucursal { get; set; }
        public int idEmpleado { get; set; }
        public int idRol { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
