//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLEPEDIDOes = new HashSet<DETALLEPEDIDO>();
            this.DETALLERECETAs = new HashSet<DETALLERECETA>();
            this.PRODUCTOXSUCURSALs = new HashSet<PRODUCTOXSUCURSAL>();
        }
    
        public int idProducto { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> esMedicamento { get; set; }
        public Nullable<int> reqPrescripcion { get; set; }
        public string Image { get; set; }
        public Nullable<int> Precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEPEDIDO> DETALLEPEDIDOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLERECETA> DETALLERECETAs { get; set; }
        public virtual PROVEEDORE PROVEEDORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOXSUCURSAL> PRODUCTOXSUCURSALs { get; set; }
    }
}
