//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUCURSAL()
        {
            this.EMPLEADOXSUCURSALs = new HashSet<EMPLEADOXSUCURSAL>();
            this.PEDIDOS = new HashSet<PEDIDO>();
            this.PRODUCTOXSUCURSALs = new HashSet<PRODUCTOXSUCURSAL>();
        }
    
        public int idSucursal { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idCanton { get; set; }
        public Nullable<int> idDistrito { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
        public string detalleDireccion { get; set; }
        public string Nombre { get; set; }
    
        public virtual CANTON CANTON { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADOXSUCURSAL> EMPLEADOXSUCURSALs { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOXSUCURSAL> PRODUCTOXSUCURSALs { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
    }
}
